---
title: "foo"
author: "Anonymous"
knit: (function(inputFile, encoding) { 
      out_dir <- "../../build";
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'report.pdf')); })
output: 
  pdf_document: 
    toc: yes
    toc_depth: 1
urlcolor: blue
bibliography: "`r here::here('src/tex', 'ref.bib')`"
---

```{r, include=FALSE}
# This chunk sets echo = TRUE as default, that is print all code.
# knitr::opts_chunk$set can be used to set other notebook generation options, too.
# include=FALSE inside curly brackets makes this block not be included in the pdf.
knitr::opts_chunk$set(echo = TRUE)
```

# Rstan models
## Separate model
```{r echo=FALSE}
code_separate <-"../stan/separate_model.stan"
writeLines(readLines(code_separate))
```
## Pooled model
```{r, echo=FALSE}
code_pooled <-"../stan/pooled_model.stan"
writeLines(readLines(code_pooled))
```
## Hierarchical model
```{r, echo=FALSE}
code_hier <-"../stan/hierarchical_model.stan"
writeLines(readLines(code_hier))
```